In [2]:
import pandas as pd
import numpy as np
import keras
from create_model import make_model

In [5]:
from prepare_data_cube_cont import make_cubes_cont

filename = 'dataframe_validation_attack.csv'
df = pd.read_csv(filename, sep=',')
allRows = df.shape[0]

IDs = df['ID']
attack = df[df['Attack'] == 'Yes'].copy()
attack_ind = attack.index

dataValues = df.drop([ "ID", "Packet Deltatime", "Attack","Attack Window Number", "Normal Window Number"], axis = 1).copy()

dataValues = dataValues.to_numpy() 
print(dataValues.shape)
n_steps = int(allRows/10000) # about 10k in each step #127 before
print(n_steps)
split = np.array_split(range(allRows), n_steps)

type = 'cnn'
modelname = '3dCNN_final'
model =  keras.models.load_model(modelname)

all_attack_errors = []
all_normal_errors = []

for y in range(2):
    print(f'{y} of {n_steps}')
    data_ind = split[y]
    
    #dfSlice = df.iloc[slice1:slice2,:].copy()
    #data, ID_vector,_ = continuous_process(dfSlice)

    t_IDs = IDs[data_ind]
    training_data = dataValues[data_ind,:]

    x_val,samples = make_cubes_cont(t_IDs,training_data,40,type,data_ind) 

    contains_attack = [np.any(np.in1d(x, attack_ind)) for x in samples]
    attack_samples = contains_attack
    no_attacks = ~np.array(contains_attack)

(346332, 64)
34
0 of 34
x shape = (254, 40, 64, 17, 1)
1 of 34
x shape = (254, 40, 64, 17, 1)


In [7]:
attack_cubes = x_val[attack_samples,:,:,:,:]
x_normal = x_val[no_attacks,:,:,:,:]

In [11]:
x_normal.shape

(248, 40, 64, 17, 1)

In [12]:
attack_cubes.shape

(6, 40, 64, 17, 1)

In [2]:
datafile =  'gear_dataset.csv'
colnames = ["time", "ID", "DLC", "Data1", \
        "Data2", "Data3", "Data4", "Data5", "Data6", "Data7", "Data8", "Attack"]


df = pd.read_csv(datafile, sep=',', names=colnames)

In [2]:
filename = 'dataframe_training_normal.zip'
df = pd.read_pickle(filename, compression='zip')
ID_vector = df['ID']

dataValues = df.drop(["Total Time", "Attack", "ID", "Packet Deltatime", "Attack Window Number", "Normal Window Number"], axis = 1).copy()

dataValues = dataValues.to_numpy()

In [10]:
filename = 'dataframe_validation_normal.csv'
df = pd.read_csv(filename, sep=',')
df.shape

(891400, 80)

In [41]:
b = int(len(a)/3)

for x in range(0,len(a)+3,3):
    first = x
    second = x+3
    print(first, second) 
    print(a[first:second])


0 3
[1. 2. 3.]
3 6
[4. 5. 6.]
6 9
[7. 8. 9.]
9 12
[10. 11. 12.]
12 15
[13. 14. 15.]
15 18
[16. 17. 18.]
18 21
[19.]
21 24
[]


In [67]:
A = np.array([0,0,1,1,2,2,3,3,4,4])
for x in range(6):
    ind = g[x]
    print(A[ind])


[0 0]
[1 1]
[2 2]
[3 3]
[4]
[4]


In [6]:
dataValues = df.drop(["Total Time", "Attack", "ID", "Packet Deltatime", "Attack Window Number", "Normal Window Number"], axis = 1).copy()
ID_vector = df['ID']

dataValues = dataValues.to_numpy()

In [48]:
dataValues[ind,:]

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0]],
      dtype=int64)

In [7]:
from cont_data_process import continuous_process
from prepare_data_cube_cont import make_cubes_cont

modelname = 'CNN_LSTM_friday'
model =  keras.models.load_model(modelname)
n_steps = dataValues.shape[0]/10000 # approx 10 000 rows in each step

#type = 'timeDist_cnn'
#type = 'cnn_lstm'
type = 'cnn'

n_timesteps = 40
allRows = df.shape[0]

for rows in range(0,dataValues.shape[0]):
    slice1 = rows
    slice2 = rows + 9999
    dfSlice = df.iloc[slice1:slice2,:].copy()
    #data, ID_vector,labeled_data = continuous_process(dfSlice
    # )

    #labeled_data = labeled_data.reset_index(drop=True)
    ID_vector = ID_vector[slice1:slice2]
    print(ID_vector.shape)
    data = dataValues[slice1:slice2,:]
    print(data.shape)
    x,samples = make_cubes_cont(ID_vector,data,n_timesteps,type) 
    #model.fit(x,x, epochs=2, verbose=2, batch_size = 1, shuffle=False)





(9999,)
(9999, 64)
x shape = (1992, 40, 64, 17, 1)
Epoch 1/2


KeyboardInterrupt: 

In [17]:
training_dataValues.shape

(1273360, 64)

In [22]:
import keras

In [27]:
model = keras.models.load_model('final trained models\cannolo_LSTM_all_IDs')
model.summary()



Model: "EncoderDecoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 40, 64)]     0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 40, 256)      16640       input_1[0][0]                    
__________________________________________________________________________________________________
dropout (Dropout)               (None, 40, 256)      0           dense[0][0]                      
__________________________________________________________________________________________________
lstm (LSTM)                     (None, 40, 128)      197120      dropout[0][0]                    
_____________________________________________________________________________________